channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - arrow-cpp=11.0.0
  - attrs=22.2.0
  - aws-c-auth=0.6.24
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.10
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.18
  - aws-c-http=0.7.4
  - aws-c-io=0.13.15
  - aws-c-mqtt=0.8.6
  - aws-c-s3=0.2.4
  - aws-c-sdkutils=0.1.7
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.19.7
  - aws-sdk-cpp=1.10.57
  - biothings_client=0.2.6
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.5.7
  - cachetools=5.3.0
  - cattrs=22.2.0
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cryptography=39.0.0
  - exceptiongroup=1.1.0
  - frozendict=2.3.4
  - gflags=2.2.2
  - glog=0.6.0
  - icu=70.1
  - idna=3.4
  - itsdangerous=2.1.2
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libabseil=20220623.0
  - libarrow=11.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=7.88.1
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - libgoogle-cloud=2.7.0
  - libgrpc=1.51.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libprotobuf=3.21.12
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libthrift=0.16.0
  - libutf8proc=2.8.0
  - libuuid=2.32.1
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lxml=4.9.2
  - lz4-c=1.9.4
  - ncurses=6.3
  - numpy=1.24.2
  - openssl=3.1.0
  - orc=1.8.2
  - packaging=23.1
  - pandas=1.5.3
  - parquet-cpp=1.5.1
  - patsy=0.5.3
  - pip=23.0.1
  - platformdirs=3.1.1
  - pooch=1.7.0
  - pyarrow=11.0.0
  - pycparser=2.21
  - pyld=2.0.3
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python-dotenv=1.0.0
  - python_abi=3.10
  - pytz=2022.7.1
  - pyyaml=6.0
  - re2=2023.02.01
  - readline=8.1.2
  - requests=2.28.2
  - requests-cache=0.9.8
  - s2n=1.3.35
  - scipy=1.10.1
  - setuptools=67.1.0
  - six=1.16.0
  - snappy=1.1.9
  - statsmodels=0.14.0
  - tk=8.6.12
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - ujson=5.7.0
  - url-normalize=1.4.3
  - urllib3=1.26.14
  - wheel=0.38.4
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - dataclasses-json==0.5.7
      - marshmallow==3.19.0
      - marshmallow-enum==1.5.1
      - more-click==0.1.2
      - mypy-extensions==1.0.0
      - pystow==0.5.0
      - tqdm==4.65.0
      - typing-inspect==0.8.0
      - zenodo-client==0.2.0
