name: /home/carlos/github/drexml-retinitis/.venvs/drugbank-parser
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - attrs=22.2.0
  - biothings_client=0.2.6
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - cachetools=5.3.0
  - cattrs=22.2.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cryptography=39.0.0
  - exceptiongroup=1.1.0
  - frozendict=2.3.4
  - icu=70.1
  - idna=3.4
  - itsdangerous=2.1.2
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libuuid=2.32.1
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lxml=4.9.2
  - ncurses=6.3
  - numpy=1.24.2
  - openssl=3.0.7
  - pandas=1.5.3
  - pip=23.0
  - pycparser=2.21
  - pyld=2.0.3
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.7.1
  - pyyaml=6.0
  - readline=8.1.2
  - requests=2.28.2
  - requests-cache=0.9.8
  - setuptools=67.1.0
  - six=1.16.0
  - tk=8.6.12
  - typing_extensions=4.4.0
  - tzdata=2022g
  - ujson=5.7.0
  - url-normalize=1.4.3
  - urllib3=1.26.14
  - wheel=0.38.4
  - xz=5.2.6
  - yaml=0.2.5
