channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - argcomplete=3.0.8
  - binutils_impl_linux-64=2.40
  - bioconductor-annotationdbi=1.60.0
  - bioconductor-annotationhub=3.6.0
  - bioconductor-biobase=2.58.0
  - bioconductor-biocbaseutils=1.0.0
  - bioconductor-biocfilecache=2.6.0
  - bioconductor-biocgenerics=0.44.0
  - bioconductor-biocversion=3.16.0
  - bioconductor-biostrings=2.66.0
  - bioconductor-data-packages=20230420
  - bioconductor-delayedarray=0.24.0
  - bioconductor-edger=3.40.0
  - bioconductor-genomeinfodb=1.34.9
  - bioconductor-genomeinfodbdata=1.2.9
  - bioconductor-genomicranges=1.50.0
  - bioconductor-hipathia=2.14.0
  - bioconductor-interactivedisplaybase=1.36.0
  - bioconductor-iranges=2.32.0
  - bioconductor-keggrest=1.38.0
  - bioconductor-limma=3.54.0
  - bioconductor-matrixgenerics=1.10.0
  - bioconductor-multiassayexperiment=1.24.0
  - bioconductor-org.hs.eg.db=3.16.0
  - bioconductor-preprocesscore=1.60.2
  - bioconductor-s4vectors=0.36.0
  - bioconductor-summarizedexperiment=1.28.0
  - bioconductor-xvector=0.38.0
  - bioconductor-zlibbioc=1.44.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.5.7
  - cairo=1.16.0
  - curl=8.1.1
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gcc_impl_linux-64=12.2.0
  - gettext=0.21.1
  - gfortran_impl_linux-64=12.2.0
  - glpk=5.0
  - gmp=6.2.1
  - graphite2=1.3.13
  - gsl=2.7
  - gxx_impl_linux-64=12.2.0
  - harfbuzz=7.3.0
  - icu=72.1
  - jq=1.5
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.1.1
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc=7.2.0
  - libgcc-devel_linux-64=12.2.0
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.76.3
  - libgomp=12.2.0
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsanitizer=12.2.0
  - libsqlite=3.42.0
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=12.2.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp-base=1.3.0
  - libxcb=1.15
  - libxml2=2.11.4
  - libzlib=1.2.13
  - make=4.3
  - ncurses=6.3
  - nlopt=2.7.1
  - numpy=1.24.3
  - openssl=3.1.0
  - pandoc=2.19.2
  - pango=1.50.14
  - pcre2=10.40
  - pip=23.1.2
  - pixman=0.40.0
  - pthread-stubs=0.4
  - python=3.11.3
  - python_abi=3.11
  - pyyaml=6.0
  - r-abind=1.4_5
  - r-admisc=0.32
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.4.1
  - r-base=4.2.3
  - r-base64enc=0.1_3
  - r-bibtex=0.5.1
  - r-biocmanager=1.30.20
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-bitops=1.0_7
  - r-blob=1.2.4
  - r-boot=1.3_28.1
  - r-broom=1.0.4
  - r-bslib=0.4.2
  - r-cachem=1.0.8
  - r-car=3.1_2
  - r-cardata=3.0_5
  - r-caret=6.0_94
  - r-cellranger=1.1.0
  - r-circlize=0.4.15
  - r-class=7.3_22
  - r-cli=3.6.1
  - r-clipr=0.8.0
  - r-clock=0.7.0
  - r-cluster=2.1.4
  - r-codetools=0.2_19
  - r-coin=1.4_2
  - r-colorspace=2.1_0
  - r-commonmark=1.9.0
  - r-conquer=1.3.3
  - r-corrplot=0.92
  - r-cowplot=1.1.1
  - r-cpp11=0.4.3
  - r-crayon=1.5.2
  - r-crosstalk=1.2.0
  - r-curl=4.3.3
  - r-data.table=1.14.8
  - r-dbi=1.1.3
  - r-dbplyr=2.3.2
  - r-dendextend=1.17.1
  - r-diagram=1.6.5
  - r-digest=0.6.31
  - r-doparallel=1.0.17
  - r-dplyr=1.1.2
  - r-dt=0.28
  - r-e1071=1.7_13
  - r-ellipse=0.4.5
  - r-ellipsis=0.3.2
  - r-emmeans=1.8.6
  - r-estimability=1.4.1
  - r-evaluate=0.21
  - r-factoextra=1.0.7
  - r-factominer=2.8
  - r-fansi=1.0.4
  - r-farver=2.1.1
  - r-fastmap=1.1.1
  - r-feather=0.3.5
  - r-filelock=1.0.2
  - r-flashclust=1.01_2
  - r-fmsb=0.7.5
  - r-fontawesome=0.5.1
  - r-forcats=1.0.0
  - r-foreach=1.5.2
  - r-foreign=0.8_84
  - r-fs=1.6.2
  - r-future=1.32.0
  - r-future.apply=1.11.0
  - r-gdata=2.19.0
  - r-generics=0.1.3
  - r-ggnewscale=0.4.9
  - r-ggplot2=3.4.2
  - r-ggpolypath=0.2.0
  - r-ggpubr=0.6.0
  - r-ggrepel=0.9.3
  - r-ggsci=3.0.0
  - r-ggsignif=0.6.4
  - r-globaloptions=0.1.2
  - r-globals=0.16.2
  - r-glue=1.6.2
  - r-gmodels=2.18.1.1
  - r-gower=1.0.1
  - r-gridbase=0.4_7
  - r-gridextra=2.3
  - r-gtable=0.3.3
  - r-gtools=3.9.4
  - r-hardhat=1.3.0
  - r-haven=2.5.2
  - r-here=1.0.1
  - r-highr=0.10
  - r-hms=1.1.3
  - r-htmltools=0.5.5
  - r-htmlwidgets=1.6.2
  - r-httpuv=1.6.11
  - r-httr=1.4.6
  - r-igraph=1.4.3
  - r-ipred=0.9_14
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-janitor=2.2.0
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.4
  - r-kernsmooth=2.23_21
  - r-knitr=1.43
  - r-labeling=0.4.2
  - r-later=1.3.1
  - r-lattice=0.21_8
  - r-lava=1.7.2.1
  - r-lazyeval=0.2.2
  - r-leaps=3.1
  - r-libcoin=1.0_9
  - r-lifecycle=1.0.3
  - r-listenv=0.9.0
  - r-lme4=1.1_33
  - r-locfit=1.5_9.7
  - r-lubridate=1.9.2
  - r-magrittr=2.0.3
  - r-maptools=1.1_6
  - r-mass=7.3_60
  - r-matrix=1.5_4.1
  - r-matrixmodels=0.5_1
  - r-matrixstats=0.63.0
  - r-memoise=2.0.1
  - r-mgcv=1.8_42
  - r-mime=0.12
  - r-minqa=1.2.5
  - r-modelmetrics=1.2.2.2
  - r-modeltools=0.2_23
  - r-multcomp=1.4_23
  - r-multcompview=0.1_9
  - r-munsell=0.5.0
  - r-mvtnorm=1.1_3
  - r-nbclust=3.0.1
  - r-nlme=3.1_162
  - r-nloptr=2.0.3
  - r-nmf=0.21.0
  - r-nnet=7.3_19
  - r-numderiv=2016.8_1.1
  - r-ontologyindex=2.10
  - r-openssl=2.0.6
  - r-openxlsx=4.2.5.2
  - r-parallelly=1.35.0
  - r-pbkrtest=0.5.2
  - r-pillar=1.9.0
  - r-pkgconfig=2.0.3
  - r-pkgmaker=0.32.10
  - r-plogr=0.2.0
  - r-plyr=1.8.8
  - r-png=0.1_8
  - r-polynom=1.4_1
  - r-prettyunits=1.1.1
  - r-proc=1.18.2
  - r-prodlim=2023.03.31
  - r-progress=1.2.2
  - r-progressr=0.13.0
  - r-promises=1.2.0.1
  - r-proxy=0.4_27
  - r-purrr=1.0.1
  - r-quantreg=5.95
  - r-r.methodss3=1.8.2
  - r-r.oo=1.25.0
  - r-r.utils=2.12.2
  - r-r6=2.5.1
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.10
  - r-rcpparmadillo=0.12.2.0.0
  - r-rcppeigen=0.3.3.9.3
  - r-rcurl=1.98_1.12
  - r-readr=2.1.4
  - r-readxl=1.4.2
  - r-recipes=1.0.6
  - r-registry=0.5_1
  - r-rematch=1.0.1
  - r-rentrez=1.2.3
  - r-reshape2=1.4.4
  - r-rio=0.5.29
  - r-rismed=2.3.0
  - r-rlang=1.1.1
  - r-rmarkdown=2.21
  - r-rngtools=1.5.2
  - r-rpart=4.1.19
  - r-rprojroot=2.0.3
  - r-rsqlite=2.3.1
  - r-rstatix=0.7.2
  - r-sandwich=3.0_2
  - r-sass=0.4.6
  - r-scales=1.2.1
  - r-scatterplot3d=0.3_44
  - r-servr=0.27
  - r-shape=1.4.6
  - r-shiny=1.7.4
  - r-snakecase=0.11.0
  - r-sourcetools=0.1.7_1
  - r-sp=1.6_0
  - r-sparsem=1.81
  - r-squarem=2021.1
  - r-statmod=1.5.0
  - r-stringi=1.7.12
  - r-stringr=1.5.0
  - r-survival=3.5_5
  - r-sys=3.4.2
  - r-th.data=1.1_2
  - r-tibble=3.2.1
  - r-tidyr=1.3.0
  - r-tidyselect=1.2.0
  - r-timechange=0.2.0
  - r-timedate=4022.108
  - r-tinytex=0.45
  - r-tzdb=0.4.0
  - r-utf8=1.2.3
  - r-varfrompdb=2.2.10
  - r-vctrs=0.6.2
  - r-venn=1.11
  - r-viridis=0.6.3
  - r-viridislite=0.4.1
  - r-vroom=1.6.3
  - r-withr=2.5.0
  - r-xfun=0.39
  - r-xml=3.99_0.14
  - r-xml2=1.3.4
  - r-xml2r=0.0.6
  - r-xtable=1.8_4
  - r-yaml=2.3.7
  - r-zip=2.3.0
  - r-zoo=1.8_12
  - readline=8.2
  - sed=4.8
  - setuptools=67.7.2
  - sysroot_linux-64=2.12
  - tk=8.6.12
  - tktable=2.10
  - toml=0.10.2
  - tomlkit=0.11.8
  - tzdata=2023c
  - wheel=0.40.0
  - xmltodict=0.13.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yq=3.2.2
  - zlib=1.2.13
  - zstd=1.5.2
